config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about/' => 'welcome#about', as: :about

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :projects, shallow:true do
    resources :goals do
      resources :tasks
    end
  end
  get '/member/edit/:id', to: 'projects#listMember', as: :editMember
  post '/member/edit/:id', to: 'projects#editMember'
  post '/member/update/:id' , to: 'projects#updateMember', as: :updateMember
  post '/member/remove/:id', to: 'projects#removeMember', as: :removeMember
  get '/projects/delete/:id', to: 'projects#deleteAllGoal', as: :deleteAll
  get '/projects/:id/update_now', to: 'projects#check_update', as: :project_update

  get '/updateFlag/:id', to: 'tasks#setFlag', as: :task_flag
  post '/updateComplete/:id', to: 'tasks#setComplete', as: :task_complete
  post '/updateTask/:id', to: 'tasks#relocateTask', as: :sort_task

  get '/logs/:id', to: 'logs#index', as: :logs
  get '/logs/history/:id', to: 'logs#show', as: :show_logs
  post '/logs/:id/new', to: 'logs#create', as: :new_log

  get '/generate/share/:id', to: 'tokens#createShare', as: :share_project
  get '/token/:hex', to: 'tokens#show', as: :show_token

  get '/message/new/:id', to: 'messages#new', as: :new_message
  post '/message/new/:id', to: 'messages#create'
  get '/message/:id', to: 'messages#show', as: :show_message
  post '/message/:id', to: 'messages#conversation'
  get '/message/', to: 'messages#index', as: :list_message
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :goal

  has_many :contributes, dependent: :destroy
  has_many :contributors, through: :contributes, source: :user

  validates :title,presence: true
  validates :deadline,presence: true
  validates :goal_id,presence: true

  after_save :update_project
  def self.getTasks(id)
    Task.where(goal_id:id).order(flagged: :desc ,deadline: :asc)
  end
  def getClassType
    str= ""
    str += (completed ? 'completed ' : "")
    str += (flagged ? 'flagged ' : "")
    str += (expired&&!completed ? 'expired ' : "")
    return str
  end

  def checkFlag()
    today = Date.today
    if(!completed && !flagged)
      if((deadline - today) <=1)
        update flagged:true
        Log.createLogTask('autoflagged',goal.project.id,self)
      end
    end
    if(!expired)
      if(deadline.past?)
        update expired:true
        Log.createLogTask('expired',goal.project.id,self)
      end
    end
    return expired
  end

  def update_project
    goal.project.update updated_at:DateTime.now()
    goal.update updated_at:DateTime.now()
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user
  before_action :authorize_admin, except: [:setComplete,:create]

  def new
  end

  def create
    @task = Task.new params.require(:task).permit([:title,:deadline, :completed,:flagged,:goal_id,user_ids:[]])
    project_id = Goal.find(params[:goal_id]).project_id
    if @task.save
      Log.createLogTask('create',project_id,@task,current_user)
      render partial: 'edit', locals:{task:@task}
    else
      render :new
    end
  end

  def destroy
    @task = Task.find params[:id]
    Log.createLogTask('destroy',@task.goal.project.id,@task,current_user)
    @task.destroy
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update params.require(:task).permit([:title,:deadline, :completed,:flagged])
    project_id = @task.goal.project_id
    Log.createLogTask('update',project_id,@task,current_user)
    redirect_to edit_project_path(@task.goal.project.id)
  end

  def setFlag
    @task = Task.find(params[:id])
    @task.flagged =  !@task.flagged
    Log.createLogTask(((@task.completed)? "flagged": "unflagged"),@task.goal.project.id,@task,current_user)
    @task.save
    render :nothing => true, :status => 204
  end

  def setComplete
    @task = Task.find(params[:id])
    @task.completed =  !@task.completed
    project_id = params[:id]
    Log.createLogTask(((@task.completed)? "checked": "unchecked"),@task.goal.project.id,@task,current_user)
    @task.save
    cookies[:timestamp] = DateTime.now();
    render :nothing => true, :status => 204
  end

  def relocateTask
    @task = Task.find(params[:id])
    @task.update params.permit([:goal_id])
  end

  def authorize_admin
    @task = Task.find(params[:id])
    unless (user_signed_in? && is_admin(@task.goal.project_id,current_user))
      redirect_to project_path(@task.goal.project_id), alert: 'access denied, you are not an admin of this project!'
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit.html.erb
<li task-id="<%= task.id %>" class="tasks">
  <div class = "<%=task.getClassType%>">
    <div>
      <div class ='info'>
        <i><%= task.title %></i>
        <p><%= task.deadline.strftime("%m/%d/%Y") %></p>
      </div>
      <div>
        <button class='btn btn-sm btn-default'><%= link_to 'Edit',edit_task_path(task.id) %> </button>
        <button class='button-flag btn btn-sm btn-default'>Urgent</button>
        <button class='btn btn-danger btn-delete btn-sm btn-remove-task'>
          <span class="glyphicon glyphicon-trash"></span>
        </button>
      </div>
    </div>
  </div>
</li>

app/views/tasks/_new.html.erb
<div class='new'>
  <li id='form' class='tasks'>
    <div id='new-task-form'>
      <%= form_tag '#',:onSubmit => "return false" do |f|  %>
        <%= label_tag :title %>
        <%= text_field_tag :title, nil, class: "form-control" %>

        <%= label_tag :deadline %>
        <%= text_field_tag :deadline,nil, class: 'form-control' %>
        <%= label_tag :completed %>
        <%= check_box_tag :completed %>

        <%= label_tag :flagged %>
        <%= check_box_tag :flagged %>
        <br>
        <%= button_tag 'New Task', class: "new-task-complete btn btn-default",id:'new-task-submit' %>
        <%= button_tag 'Cancel',id:'new-task-cancel', class: "new-task-cancel btn btn-default" %>
      <% end %>
    </div>
  </li>
  <hr>
</div>

app/views/tasks/_share.html.erb
<li class="<%=task.getClassType%>">
  <div class='show-task'>
    <div class='info'>
      <i><%= task.title %></i>
      <p><%= task.deadline.strftime("%m/%d/%Y") %></p>
    </div>
  </div>
</li>

app/views/tasks/_task.html.erb
<li task-id="<%= task.id %>" class="<%=task.getClassType%>" expired="<%= task.checkFlag()%>">
  <div class='show-task'>
    <% if true %>
      <label class="switch" switch-id="<%= task.id %>">
        <input class="checkbox" type="checkbox" check-id="<%= task.id %>" <%= (task.completed)?"checked='true'":"" %>>
        <div class="slider round"></div>
      </label>
    <% end %>
    <div class='info'>
      <i><%= task.title %></i>
      <p><%= task.deadline.strftime("%m/%d/%Y") %></p>
    </div>
  </div>
</li>

app/views/tasks/edit.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title %>
  <%= f.input :deadline,as: :string,:input_html => {:class=>"datepicker"}%>
  <%= f.input :completed %>
  <%= f.input :flagged %>
  <%= f.submit 'Update' , {:class=>"btn btn-default"}%>
  <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
<% end %>

app/views/tasks/new.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title %>
  <%= f.input :goal_id, :collection => @goals,selected: 1 %>
  <%= f.input :deadline,as: :string , {:class=>"datepicker"}%>
  <%= f.input :completed %>
  <%= f.input :flagged %>
  <%= f.submit 'Update' , {:class=>"btn btn-default"}%>
  <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
<% end %>