config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about/' => 'welcome#about', as: :about

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :projects, shallow:true do
    resources :goals do
      resources :tasks
    end
  end
  get '/member/edit/:id', to: 'projects#listMember', as: :editMember
  post '/member/edit/:id', to: 'projects#editMember'
  post '/member/update/:id' , to: 'projects#updateMember', as: :updateMember
  post '/member/remove/:id', to: 'projects#removeMember', as: :removeMember
  get '/projects/delete/:id', to: 'projects#deleteAllGoal', as: :deleteAll
  get '/projects/:id/update_now', to: 'projects#check_update', as: :project_update

  get '/updateFlag/:id', to: 'tasks#setFlag', as: :task_flag
  post '/updateComplete/:id', to: 'tasks#setComplete', as: :task_complete
  post '/updateTask/:id', to: 'tasks#relocateTask', as: :sort_task

  get '/logs/:id', to: 'logs#index', as: :logs
  get '/logs/history/:id', to: 'logs#show', as: :show_logs
  post '/logs/:id/new', to: 'logs#create', as: :new_log

  get '/generate/share/:id', to: 'tokens#createShare', as: :share_project
  get '/token/:hex', to: 'tokens#show', as: :show_token

  get '/message/new/:id', to: 'messages#new', as: :new_message
  post '/message/new/:id', to: 'messages#create'
  get '/message/:id', to: 'messages#show', as: :show_message
  post '/message/:id', to: 'messages#conversation'
  get '/message/', to: 'messages#index', as: :list_message
end

app/models/project.rb
class Project < ApplicationRecord
  # has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :goals, lambda { order(created_at: :DESC) }, dependent: :destroy
  has_many :logs, lambda { order(created_at: :DESC) }, dependent: :destroy

  has_many :members, dependent: :destroy
  has_many :contributors, through: :members, source: :user

  has_many :leadings, dependent: :destroy
  has_many :leaders, through: :leadings, source: :user


  validates :title,presence: true
  validates :deadline,presence: true
  validates :status,presence: true

  def getTimeLeft
    today = Date.today
    remain = (deadline.mjd - today.mjd)
    return ((remain<0)? 'Expired' : "#{remain} Days")
  end

  def getTimeClass
    today = Date.today
    remain = (deadline.mjd - today.mjd)
    return ((remain<0)? 'Expired' : "")
  end

  def is_member(user)
    return contributors.find(user).present?
  end

  def checkUser(user)
    return (leaders.find_by(id:user.id).nil?)? 'Member' : 'Admin'
  end

  def updateTime
    return updated_at.strftime('%d %b %Y %H:%M')
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, except: [:index,:new,:create]
  before_action :authorize_access, except: [:index,:new,:create]
  before_action :authorize_admin, except: [:index,:new,:create,:show]
  before_action :authenticate_user, only: [:index,:new,:create]
  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if@project.save
      Leading.create(project:@project, user:current_user)
      Member.create(project:@project, user:current_user)
      Log.createLogProject('create',@project.id,@project,current_user)
      redirect_to edit_project_path(@project.id)
    else
      flash.now[:alert] = 'Please see errors below'
      render :new
    end
  end

  def update
    if @project.update project_params
      @project.update deadline:params[:project][:deadline].to_date
      flash[:notice] = 'Project updated'
      Log.createLogProject('update',@project.id,@project,current_user)
      redirect_to(:back)
    else
      flash.now[:alert] = 'Please see errors below!'
      render :edit
    end
  end

  def edit
  end

  def listMember
  end

  def editMember
    user = User.find(params[:user_id])
    admin = Leading.find_by(project_id: @project.id, user:user)
    if admin
      admin.destroy
      Log.createLogMember('downgrade',@project.id,current_user,user)
    else
      Leading.create(project_id:@project.id,user_id:user.id)
      Log.createLogMember('promot',@project.id,current_user,user)
    end
    redirect_to :back
  end

  def removeMember
    user_id = params[:user_id]
    user = Member.find_by(user_id:user_id,project_id:@project.id)
    Log.createLogMember('remove',@project.id,current_user,User.find(user_id))
    user.destroy
    user = Leading.find_by(user_id:user_id,project_id:@project.id)
    if user
      user.destroy
    end
    redirect_to :back
  end

  def updateMember
    members = params[:user][:user_id]
    members.each do |member|
      unless Member.find_by(user_id:member,project:@project)
        if(member!='')
          Member.create(user_id:member,project:@project)
          Log.createLogMember('add',@project.id,current_user,User.find(member))
        end
      end
    end
    redirect_to :back
  end

  def index
    @projects = []
    if(user_signed_in?)
      @projects = current_user.join_project
    end
  end

  def show
    cookies[:timestamp] = DateTime.now();
  end

  def destroy
    @project.destroy
    redirect_to root_path, notice: 'Project deleted'
  end

  def check_update
    if @project.updated_at>=cookies[:timestamp]
      render json: {reload:true}
    else
      render json: {reload:false}
    end
  end

  def deleteAllGoal
    @project.goals.each do |goal|
      goal.destroy
    end
    Log.createLogProject('deleteAll',@project.id,@project,current_user)
    redirect_to project_path(@project)
  end
  private

  def authorize_access
    unless (user_signed_in? && @project.is_member(current_user))
      redirect_to root_path, alert: 'access denied, you have no access to this project!'
    end
  end

  def authorize_admin
    unless (user_signed_in? && is_admin(@project.id,current_user))
      redirect_to project_path(@project.id), alert: 'access denied, you are not an admin of this project!'
    end
  end
  def project_params
    params.require(:project).permit([:title, :description,:deadline,:status,id: []])
  end

  def find_project
    @project = Project.find params[:id]
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= @project.errors.full_messages.join(', ') %>

<%= simple_form_for @project do |f| %>
  <div>
    <%= f.input :title %>
  </div>

  <div>
    <%= f.input :description %>
  </div>

  <div>
    <%= f.input :deadline,as: :string,:input_html => {:class=>"datepicker"}%>
  </div>

  <div>
    <%= f.input :status, :collection => %w[In-Progress Canceled  Completed],selected: 1 %>
  </div>

  <%= f.submit btn_label,{class:'btn btn-md btn-success'}%>
<% end %>

app/views/projects/_menu.html.erb
<% if is_admin(id,current_user) %>
    <%= link_to 'Project Home', project_path(id) ,{ :class => "btn btn-primary btn-lg" } %>
    <%= link_to 'Edit Project', edit_project_path(id) ,{ :class => "btn btn-primary btn-lg" } %>
    <%= link_to 'Members', editMember_path ,{ :class => "btn btn-primary btn-lg" } %>

    <%= link_to 'Generate Sharable link', share_project_path(id) ,{ :class => "btn btn-primary btn-delete btn-lg" } %>
    <%= link_to 'Project Logs',logs_path(id),{ :class => "btn btn-primary btn-lg" } %>
    <button class='btn-delete btn btn-danger btn-lg'>
      <%= link_to 'Delete Project', project_path(id),
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
    </button>
<hr>
<% end %>

app/views/projects/_share.html.erb
<div class = 'project-info'>
  <h1> Project Info </h1>
  <h2><%= project.title %></h2>
  <p>Project description: <%= project.description %></p>
  <p>Team Members: <%= project.contributors.map(&:name).join(', ') %></p>
</div>

<hr>
<% project.goals.each do| goal| %>
  <%= render '/goals/share', goal:goal %>
<% end %>

app/views/projects/edit.html.erb
<%= javascript_include_tag "project-edit" %>
<h1>Update Project</h1>

<%= render 'menu', id:@project.id %>

<div class='project-edit-info'>
  <h1> Project Info</h1>
  <%= render 'form', { btn_label: 'Update' } %>
  <hr>
</div>

<div>
  <h1>
    Goals and Tasks
  </h1>
  <p>
    <button id='add-goal' class = 'btn btn-default'>New Goal</button>
    <button class='btn btn-danger btn-delete'><%= link_to "Delete All Goals" ,deleteAll_path(@project)%></button>
    Total Number of Goals: <span id='goal-count'><%= @project.goals.size %></span>
  </p>
  <hr>
  <br>
  <%# render 'goals/new' %>
  <div id='goals' project_id="<%= @project.id %>">
    <% @project.goals.each do| goal| %>
      <%= render '/goals/edit', goal:goal %>
    <% end %>
  </div>
</div>

<div id='new-goal-form-section' class='hidden task-form'>
  <%= render 'goals/new' %>
</div>

<div id='new-task-form-section' class='hidden goal-form'>
  <%= render 'tasks/new' %>
</div>

app/views/projects/index.html.erb
<h1> All Contributing Project </h1>
<hr>
<% @projects.each do |project| %>
  <div class='project-detail <%= project.checkUser(current_user) %>'>
    <h2><%= link_to project.title, project_path(project) %></h2>
    <p><%= "Status: "+project.status %><p>
    <p><%= "Deadline: "+project.deadline.strftime("%m/%d/%Y") %></p>
    <p class="<%= project.getTimeClass %>"><%= "Day Remaining: "+project.getTimeLeft %></p>
    <p>Last update: <%= project.updateTime %></p>
  </div>
  <hr>
<% end %>

app/views/projects/listMember.html.erb
<%= render 'menu', id:@project.id %>

<h1>Project Members</h1>
<div>
  <h2>Members: </h2>
  <table id='membersList' class = 'member-table table table-bordered table-hover'>
    <% @project.contributors.each do| member| %>
      <tr>
          <td><%= member.name %></td>
          <td class="<%= @project.checkUser(member) %>">
            <% if member!=current_user %>
              <%= link_to @project.checkUser(member),editMember_path(@project, user_id:member.id),method: :post %>
            <% end %>
          </td>
          <td class=''><% if member!=current_user %>
            <%= link_to "x",removeMember_path(@project, user_id:member.id),method: :post,class:'remove'%>
          <% end %>
          </td>
      </tr>
    <% end %>
  </table>
</div>
<hr>

<div class='addMember-widget'>
  <h2>Add Member</h2>
  <br>
  <%= form_tag  updateMember_path(@project.id) do  %>
  <div>
      <%= collection_select(
      :user,:user_id,User.all,
      :id,:name,
      {},
      {multiple: true, class: 'chosen-select'}) %>
  </div>
    <%= submit_tag "Submit", class:'btn btn-success btn-lg' %>
  <% end %>
</div>
<script>
  $('.chosen-select').chosen({ width: '500px' });
</script>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', { btn_label: 'Create' } %>

app/views/projects/show.html.erb
<%= javascript_include_tag('project-show.js') %>
<%= render 'menu', id:@project.id %>
<div class = 'project-info'>
  <h1 id='title' project-id="<%= @project.id %>"> Project Info </h1>
  <p>Project Title : <%= @project.title %></p>
  <p>Project description: <%= @project.description %></p>
  <p>Project Deadline: <%= @project.deadline.strftime("%m/%d/%Y") %></p>
  <p>Time Remaining: <%= @project.getTimeLeft %></p>
  <p>Last update: <%= @project.updateTime %></p>
  <p>Team Admins: <%= @project.leaders.map(&:name).join(', ') %></p>
  <p>Team Members:
    <% @project.contributors.each_with_index do |user,index| %>
      <%= ',' unless index==0 %>
      <%= link_to user.name,new_message_path(user.id)%>
    <% end %>
  </p>
</div>
<hr>
<% @project.goals.each do| goal| %>
  <%= render '/goals/goal', goal:goal %>
<% end %>