config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about/' => 'welcome#about', as: :about

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :projects, shallow:true do
    resources :goals do
      resources :tasks
    end
  end
  get '/member/edit/:id', to: 'projects#listMember', as: :editMember
  post '/member/edit/:id', to: 'projects#editMember'
  post '/member/update/:id' , to: 'projects#updateMember', as: :updateMember
  post '/member/remove/:id', to: 'projects#removeMember', as: :removeMember
  get '/projects/delete/:id', to: 'projects#deleteAllGoal', as: :deleteAll
  get '/projects/:id/update_now', to: 'projects#check_update', as: :project_update

  get '/updateFlag/:id', to: 'tasks#setFlag', as: :task_flag
  post '/updateComplete/:id', to: 'tasks#setComplete', as: :task_complete
  post '/updateTask/:id', to: 'tasks#relocateTask', as: :sort_task

  get '/logs/:id', to: 'logs#index', as: :logs
  get '/logs/history/:id', to: 'logs#show', as: :show_logs
  post '/logs/:id/new', to: 'logs#create', as: :new_log

  get '/generate/share/:id', to: 'tokens#createShare', as: :share_project
  get '/token/:hex', to: 'tokens#show', as: :show_token

  get '/message/new/:id', to: 'messages#new', as: :new_message
  post '/message/new/:id', to: 'messages#create'
  get '/message/:id', to: 'messages#show', as: :show_message
  post '/message/:id', to: 'messages#conversation'
  get '/message/', to: 'messages#index', as: :list_message
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :project
  has_many :tasks, lambda { order(created_at: :DESC) }, dependent: :destroy

  validates :title,presence: true
  validates :deadline,presence: true
  validates :project_id,presence: true

  after_save :update_project

  def getCompletionRate
      total = tasks.size
      completed = tasks.where(completed:true).count

      return '100' if total==0;
      return '0' if completed==0;
      return "#{completed*100/total}"
  end

  def getCompleted
    return tasks.where(completed:true).count
  end

  def getTotal
    return tasks.size
  end

  def getTasks
    return tasks.order(expired: :desc ,flagged: :desc ,deadline: :asc)
  end

  def update_project
    project.update updated_at:DateTime.now()
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :authenticate_user
  before_action :authorize_admin
  def new
  end

  def create
    @goal = Goal.new params.require(:goal).permit([:title,:deadline, :description,:project_id])
    if goal.save
      Log.createLogGoal('create',@goal.project.id,@goal,current_user)
      render partial: 'edit', locals:{goal:@goal}
    else
      redirect_to(:back)
    end
  end

  def destroy
    Log.createLogGoal('destroy',@goal.project.id,@goal,current_user)
    @goal.destroy
  end

  def edit
  end

  def update
    @goal.update params.require(:goal).permit([:title,:deadline, :description ])
    Log.createLogGoal('update',@goal.project.id,@goal,current_user)
    redirect_to(edit_project_path(@goal.project))
  end

  def authorize_admin
    @goal = Goal.find(params[:id])
    unless (user_signed_in? && is_admin(@goal.project_id,current_user))
      redirect_to project_path(@goal.project_id), alert: 'access denied, you are not an admin of this project!'
    end
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_edit.html.erb
<div class='edit-goal' goal-id="<%= goal.id %>">
  <div class='info'>
    <label><h2><%= goal.title %></h2></label>
    <br>
    <button class=" btn btn-default btn-sm"><%= link_to 'Edit', edit_goal_path(goal.id) %></button>
    <button class="addTask btn btn-default btn-sm">Add Tasks</button>
    <button class='saveTasks btn btn-default btn-sm'>Save</button>
    <button class='btn-delete btn btn-danger btn-sm btn-remove-goal'>
      Delete
    </button>
    <h4>Description: <%= goal.description %></h4>
    <h5>Deadline: <%= goal.deadline.strftime("%m/%d/%Y") %> </h5>
    <hr>
  </div>
  <ul class='goallist' goal-id="<%= goal.id %>">
    <!-- <li class='tasks'>
      <%= render '/tasks/new' %>
    </li> -->
    <% tasks = Task.getTasks(goal.id) %>
    <% tasks.each do |task| %>
      <%= render '/tasks/edit', task:task %>
    <% end %>
  </ul>
  <hr>
</div>

app/views/goals/_goal.html.erb
<div class='goal-item'>
  <label>
    <h2><%= goal.title %></h2>
    <p><%= goal.description %></p>
    <b> Completion: %<span class="completion-<%= goal.id %>"><%= goal.getCompletionRate %></span></b>
    <div id="progress-<%= goal.id %>"
          completed = "<%= goal.getCompleted %>"
          total = "<%= goal.getTotal %>">
    </div>
    <script>$("#progress-<%= goal.id %>").progressbar({
        value: <%= goal.getCompletionRate %>
      });</script>
  </label>
  <ul class="goal" goal-id="<%= goal.id %>">
    <% tasks = Task.getTasks(goal.id) %>
    <% tasks.each do |task| %>
      <%= render '/tasks/task', task:task %>
    <% end %>
  </ul>
</div>
<hr>

app/views/goals/_new.html.erb
<div class='new-form'><ul class='goallist'>
  <div id='new-goal-form'>
    <%= form_tag '#',:onSubmit => "return false" do |f|  %>

      <%= label_tag :title %>
      <%= text_field_tag :title, nil, class: "form-control" %>

      <%= label_tag :description %>
      <%= text_area_tag :description, nil, class: "form-control" %>

      <%= label_tag :deadline %>
      <%= text_field_tag :deadline,nil, class: 'form-control' %>

      <br>
      <%= button_tag 'New Goal', class: "new-goal-complete btn btn-default",id:'new-goal-submit' %>
      <%= button_tag 'Cancel',id:'new-goal-cancel', class: "new-task-cancel btn btn-default" %>
    <% end %>
  </div>
</ul><hr></div>

app/views/goals/_share.html.erb
<div class='goal-item'>
  <label>
    <h2><%= goal.title %></h2>
    <p><%= goal.description %></p>
    <b> Completion:</b>
    <div id="progress-<%= goal.id %>"
          completed = "<%= goal.getCompleted %>"
          total = "<%= goal.getTotal %>">
    </div>
    <script>$("#progress-<%= goal.id %>").progressbar({
        value: <%= goal.getCompletionRate %>
      });</script>
  </label>
  <ul class="goal">
    <% tasks = Task.getTasks(goal.id) %>
    <% tasks.each do |task| %>
      <%= render '/tasks/share', task:task %>
    <% end %>
  </ul>
</div>
<hr>

app/views/goals/edit.html.erb
<%= simple_form_for @goal do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :deadline,as: :string,:input_html => {:class=>"datepicker"}%>
  <%= f.submit 'Update' , {:class=>"btn btn-default"}%>
  <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
<% end %>