config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/about/' => 'welcome#about', as: :about

  resources :users, only: [:create, :new]
  resources :sessions, only: [:create, :new] do
    delete :destroy, on: :collection
  end

  resources :projects, shallow:true do
    resources :goals do
      resources :tasks
    end
  end
  get '/member/edit/:id', to: 'projects#listMember', as: :editMember
  post '/member/edit/:id', to: 'projects#editMember'
  post '/member/update/:id' , to: 'projects#updateMember', as: :updateMember
  post '/member/remove/:id', to: 'projects#removeMember', as: :removeMember
  get '/projects/delete/:id', to: 'projects#deleteAllGoal', as: :deleteAll
  get '/projects/:id/update_now', to: 'projects#check_update', as: :project_update

  get '/updateFlag/:id', to: 'tasks#setFlag', as: :task_flag
  post '/updateComplete/:id', to: 'tasks#setComplete', as: :task_complete
  post '/updateTask/:id', to: 'tasks#relocateTask', as: :sort_task

  get '/logs/:id', to: 'logs#index', as: :logs
  get '/logs/history/:id', to: 'logs#show', as: :show_logs
  post '/logs/:id/new', to: 'logs#create', as: :new_log

  get '/generate/share/:id', to: 'tokens#createShare', as: :share_project
  get '/token/:hex', to: 'tokens#show', as: :show_token

  get '/message/new/:id', to: 'messages#new', as: :new_message
  post '/message/new/:id', to: 'messages#create'
  get '/message/:id', to: 'messages#show', as: :show_message
  post '/message/:id', to: 'messages#conversation'
  get '/message/', to: 'messages#index', as: :list_message
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesome Projects!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
  <nav class="navbar navbar-inverse ">
    <div class="container-fluid">
      <div class="navbar-header">
        <button
          type="button"
          class="navbar-toggle collapsed"
          data-toggle="collapse"
          data-target="#gmptool-navbar">
          <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
        </button>
        <span
        class="glyphicon glyphicon-list-alt navbar-brand"
        aria-hidden="true"></span>
      </div>

        <div class="navbar-collapse collapse" id="gmptool-navbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'New Project', new_project_path %></li>
              <li><%= link_to 'My Projects', projects_path %></li>
              <li><%= link_to 'My Messages', list_message_path %></li>
            <% end %>
            <li><%= link_to 'Contact Us', about_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><p class="navbar-text">Hello <%= current_user.first_name %></p></li>
              <li>
                <%= link_to 'Sign out',
                  sessions_path,
                  method: :delete
                  %>
                </li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_path %></li>
              <li><%= link_to 'Sign In', new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <div class="body container-fluid">
    <% if notice || alert %>
      <div
        class="alert alert-<%= notice ? 'success' : 'danger'%> alert-dismissable"
        role="alert">
        <%= notice || alert %>
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
    <a href="javascript:" id="return-to-top"><i class="glyphicon glyphicon-chevron-up"></i></a>
  </div>


</body>

<footer>
    <div class="panel-footer footer navbar-fixed-bottom">Awesome Projects - Get your project done</div>
</footer>

</html>